### ISSUE TITLE
Job using matrix report spans in same trace

### ISSUE THREAD

**Issue by janpio** [kvrhdn/gha-buildevents#13]
Hey,

just played around with your action a bit. The workflow I tried to use makes use of the matrix feature of Github Actions, but I found that this is currently not supported cleanly:

![image](https://user-images.githubusercontent.com/183673/92612222-f4505b80-f2b9-11ea-9619-bdc04bca9495.png)

See the code of the workflow in a PR that I opened to demonstrate this problem: https://github.com/kvrhdn/gha-buildevents/pull/12/files

![image](https://user-images.githubusercontent.com/183673/92612436-2a8ddb00-f2ba-11ea-99f5-015365d8249b.png)

I think one would assume to have two separate traces, one for `a` and one for `b` with the spans created in that run.

**Comment by kvrhdn** [comment]
Ouch, that's not okay. We currently rely on several environment variables to generate unique trace IDs for every job, but don't consider matrix builds yet.
I'll have to investigate whether it's possible to detect from within GitHub Actions whether the job is part of a matrix.

I can already tell you though that it will be difficult to create a single trace that contains both jobs. To get a proper trace, only one process should finish the trace. It is not possible (currently) to synchronize between both jobs, so both will try to finish the same trace creating conflicting information in Honeycomb.

You can see it in the UI when this happens:
<img width="408" alt="Screenshot 2020-09-09 at 17 20 47" src="https://user-images.githubusercontent.com/7748404/92618707-ee11ad80-f2c0-11ea-82f6-a9d1d9ecc907.png">

**Comment by janpio** [comment]
Oh yeah, sorry if that was not clear, I would totally expect 2 separate traces for these jobs.

**Comment by DavidS** [comment]
I could separate all the steps successfully by adding the matrix parameters to the STEP_ID: https://github.com/puppetlabs/puppetlabs-testing/pull/310 

Something similar could work for the TRACE_ID, if a tunable were exposed on the action.

**Comment by kvrhdn** [comment]
Hi, this is now implemented thanks to @DavidS! To create a unique trace for each matrix job add the `matrix-key` property:

```yaml
      - uses: kvrhdn/gha-buildevents@main
        with:
          apikey: ${{ secrets.HONEYCOMBIO_APIKEY }}
          dataset: <your dataset>
          job-status: ${{ job.status }}
          matrix-key: ${{ matrix.value }} # create a unique string for every matrix value
```

You can also combine multiple matrices into a single key, as David has done here: https://github.com/puppetlabs/puppetlabs-testing/blob/4ed29b68fbdb4b52aff7f521b1bb1a82633dfa44/.github/workflows/pr_test.yml#L88:L93
