### ISSUE TITLE
Provide a mechanism to add arbitrary fields to the Honeycomb event

### ISSUE THREAD

**Issue by kvrhdn** [kvrhdn/gha-buildevents#3]
`buildevents` allows you to provide arbitrary key-value data using the `BUILDEVENT_FILE` environment variable. `gha-buildevents` uses this to send metadata about the GitHub Actions workflow.

We should provide a mechanism to allow users to provide additional fields.

This syntax would be great:

```yaml
- uses: kvrhdn/gha-buildevents@master
  with:
    apikey: ${{ secrets.APIKEY }}
    dataset: my-dataset
    additional-fields:
      buildVersion: BUILD_VERSION
      project: my-project
      ...
```

**Comment by kvrhdn** [comment]
It could be interesting to allow steps to add to this file as well. I.e. in case we make a `gha-buildevents-step`:

```yaml
- uses: kvrhdn/gha-buildevents-step@master
  with:
    name: My step
    additional-fields:
      buildResult: success
```

**Comment by DavidS** [comment]
That would be great! As it stands, even trying to used the buildevent file is not really reliable as some spans don't pick up the values.

**Comment by kvrhdn** [comment]
I currently don't have any bandwidth to work on this, but I'll leave some notes here for anyone that wants to pick this up.

This issue can be divided into two problems:
1. we need a mechanism to pass arbitrary fieds to the action
2. we need a mechanism to pass these fields to the buildevents binary

For 2) we already have some infrastructure in place: buildevents already reads a file `buildevents.txt` that contains values in the [logfmt format](https://brandur.org/logfmt).
This file is created here:
- https://github.com/kvrhdn/gha-buildevents/blob/5be4636b81803713c94d7cb7e3a4b85d759df112/src/index.ts#L54-L72
- https://github.com/kvrhdn/gha-buildevents/blob/5be4636b81803713c94d7cb7e3a4b85d759df112/src/buildevents.ts#L30-L33

For 1) there is currently no solution. Additionally, I think the action inputs are currently limited to strings only. So the following is not possible:
```yaml
- uses: kvrhdn/gha-buildevents
  with:
    # snip
    additional-fields:
      - app: my-app
      - version: 0.0.1
```
Instead, we'll have to pass a text block I think:
```yaml
- uses: kvrhdn/gha-buildevents
  with:
    # snip
    additional-fields: |
      app=my-app
      version=0.0.1
```
But... can we validate this? (Do we have to validate this?)

I did something similar in my tfe-run action to pass a list of variables to Terraform:
- https://github.com/kvrhdn/tfe-run/blob/b4d4b27940dcd146b357724817ea8e3ffd01fee7/action.yaml#L54-L57
- https://github.com/kvrhdn/tfe-run/blob/b4d4b27940dcd146b357724817ea8e3ffd01fee7/.github/workflows/integration.yaml#L33-L34
